- name: run drone server
  docker_container:
    name: drone-server
    image: "{{ drone_dockerhub_namespace }}/drone:{{drone_version}}"
    state: started
    restart_policy: always
    ports:
      - "8000:8000"
      - "9000:9000"
      - "127.0.0.1:8080:80"
      - "127.0.0.1:8443:443"
    volumes:
      - /drone:/var/lib/drone/
    env:
      DRONE_SERVER_HOST: "{{drone_server_host}}"
      DRONE_SERVER_ADDR: ":8000"
      DRONE_SERVER_PROTO: "https"
      DRONE_LOGS_DEBUG: "true"
      DRONE_RPC_SECRET: "{{drone_rpc_secret}}"
      DRONE_DATABASE_DRIVER: "{{drone_database_driver}}"
      DRONE_DATABASE_DATASOURCE: "{{ drone_mysql if drone_database_driver == 'mysql' else drone_postgres }}"
      DRONE_GITEA: "{{drone_integration == 'gitea'}}"
      DRONE_GITEA_SERVER: "{{drone_gitea_server}}"
      DRONE_GITEA_CLIENT_ID: "{{drone_gitea_client_id}}"
      DRONE_GITEA_CLIENT_SECRET: "{{drone_gitea_client_secret}}"
      DRONE_USER_CREATE: "{{drone_user_create}}"
      DRONE_GITHUB_CLIENT_ID: "{{drone_github_client_id}}"
      DRONE_GITHUB_CLIENT_SECRET: "{{drone_github_client_secret}}"
      DRONE_GITHUB_SKIP_VERIFY: "true"
  tags:
    - drone
    - server

- name: run drone agent
  docker_container:
    name: "agent-{{item.name}}"
    image: "{{ drone_dockerhub_namespace }}/agent:{{drone_version}}"
    privileged: yes
    state: started
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone-server
    env:
      DRONE_RPC_SERVER: "drone-server:9000"
      DRONE_RPC_SECRET: "{{drone_rpc_secret}}"
      DRONE_LOGS_DEBUG: "true"
  with_items: "{{drone_agents}}"
  tags:
    - drone
    - agent
